FROM php:8.2-apache

RUN apt-get update && apt-get install -y \
    libfreetype6-dev \
    libjpeg62-turbo-dev \
    libpng-dev \
    libzip-dev \
    libonig-dev \
    libxml2-dev \
    unzip \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install -j$(nproc) gd pdo pdo_mysql zip bcmath opcache pcntl

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
RUN curl -sL https://deb.nodesource.com/setup_14.x | bash -
RUN apt-get install -y nodejs
RUN apt-get install -y npm

WORKDIR /var/www/alegra

COPY . .
COPY ./deploy-files/restaurant-host.conf /etc/apache2/sites-available/
COPY ./deploy-files/apache2.conf /etc/apache2/

RUN chown -R www-data:www-data /var/www/alegra
RUN a2ensite restaurant-host

RUN composer install --no-interaction --no-scripts --no-autoloader --no-dev
RUN composer dumpautoload --optimize --classmap-authoritative
RUN npm install

ENTRYPOINT [ "./deploy-files/deploy_1.sh" ]

EXPOSE 80